apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: react-frontend
  ports:
    - port: 3000  # this is the port of service, for easy write same port that is defined in targetPort.
      targetPort: 3000  # this is the pod port, on which actual service is running.  Write here the that is defined in deployment.
      nodePort: 30006 # finally, this is port of instance/node, on which we request for web application. range is 30000-32767.
  type: NodePort


                                            # so if we do curl http://192.168.31.2:30006                                
                                            # then we can access the website

                                            # Single Node (worker) demo
                                            
                                            #          +----------------+
                                            #          |      User      |
                                            #          +----------------+
                                            #                |
                                            #                |
                                            #                |
                                            #                |
                                            #                ᐯ
                                            #+------------------------------------+ 
                                            #|             NodePort               |            
                                            #|               30006                | 
                                            #|                |                   | 
                                            #|                |                   | 
                                            #|                |                   | 
                                            #|                ᐯ                   | 
                                            #|         +------------------+       |
                                            #|          |    Service       |      |
                                            #|          | IP: 10.106.1.12  |      |
                                            #|          |    Port: 80      |      |
                                            #|          +------------------+      |  
                                            #|                  |                 | 
                                            #|                  |                 | 
                                            #|                  |                 | 
                                            #|                  |                 | 
                                            #|                  |                 | 
                                            #|                  ᐯ                 | 
                                            #|           +-----------------+      | 
                                            #|           |   POD           |      | 
                                            #|           | IP: 10.244.0.2  |      | 
                                            #|           | targetPort: 80  |      | 
                                            #|           +-----------------+      | 
                                            #|                                    | 
                                            #|           Node                     |
                                            #|       192.168.31.2                 |
                                            #++----------------------------------++        


                          # Multiple Node (workers) demo

                    #                       +----------------+
                    #                       |      User      |
                    #                       +----------------+
                    #                              ||
                    #                              ||
                    #                              ||
                    #                              ||
                    #                              ||
                    #                              || 
                    #                              || 
                    #+--------------------+\\---------------------+\\+-------------------------+\\
                    #|     Node 1         |//|      Node 2         |//|      Node 3            |  
                    #|   192.168.1.2      |//|    192.168.1.3      |//|    192.168.1.4         |
                    #|     ++--------------------------------------------------------++        | 
                    #|     |                  Service                                 |        | 
                    #|     |                                                          |        |
                    #|     ++--------------------------------------------------------++        |
                    #| +------------+     |//| +------------+     |//| +-------------+         |
                    #| |  POD       |     |//| |   POD      |     |//| |   POD       |         | 
                    #| | 10.244.0.3 |     |//| | 10.244.0.4 |     |//| | 10.244.0.5  |         |
                    #| |            |     |//| |            |     |//| |             |         |
                    #| +-----------++     |//| +------------+     |//| +-------------+         |
                    #|                    |//|                    |//|                         |
                    #|                    |//|                    |//|                         |
                    #|                    |//|                    |//|                         |
                    #|                    |//|                    |//|                         |
                    #|                    |//|                    |//|                         |
                    #+--------------------+\\+--------------------+\\+-------------------------+\\
                    
